# Generated by Django 5.0.14 on 2025-05-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Lỗi', 'Lỗi'), ('Tính năng', 'Tính năng'), ('Cải tiến', 'Cải tiến')], default='Work', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Thấp', 'Thấp'), ('Trung bình', 'Trung bình'), ('Cao', 'Cao')], default='Medium', max_length=10),
        ),
    ]
