# Generated by Django 5.0.14 on 2025-05-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0003_worklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkLog',
        ),
    ]
