# Generated by Django 5.0.14 on 2025-05-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0004_delete_worklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedtask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='finishedtask',
            name='assigned_to',
            field=models.ManyToManyField(to='ETMDAPP.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(to='ETMDAPP.employee'),
        ),
    ]
