# Generated by Django 5.0.14 on 2025-05-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0005_remove_finishedtask_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='newemail',
        ),
    ]
