# Generated by Django 5.0.14 on 2025-05-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0006_remove_employee_newemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
