# Generated by Django 5.0.14 on 2025-05-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0007_remove_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_id',
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Nhẹ', 'Nhẹ'), ('Vừa', 'Vừa'), ('Nặng', 'Nặng')], default='Work', max_length=20),
        ),
    ]
