# Generated by Django 5.0.14 on 2025-05-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0008_remove_admin_admin_id_admin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('light', 'Nhẹ'), ('medium', 'Vừa'), ('heavy', 'Nặng')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], default='medium', max_length=10),
        ),
    ]
