# Generated by Django 5.0.14 on 2025-05-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0009_alter_task_category_alter_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Nhập phần trăm hoàn thành từ 0 đến 100')),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETMDAPP.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETMDAPP.task')),
            ],
            options={
                'unique_together': {('employee', 'task')},
            },
        ),
    ]
