# Generated by Django 5.0.14 on 2025-05-12 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0010_taskassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignment',
            old_name='progress_percentage',
            new_name='progress',
        ),
    ]
