# Generated by Django 5.0.14 on 2025-05-13 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0011_rename_progress_percentage_taskassignment_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedtask',
            name='task',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='ETMDAPP.task'),
            preserve_default=False,
        ),
    ]
