# Generated by Django 5.0.14 on 2025-05-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ETMDAPP', '0012_finishedtask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedtask',
            name='task',
        ),
    ]
