from django.urls import path
from . import views

urlpatterns = [
    path("", views.HOME, name="HOME"),
    path("CONTACT", views.CONTACT, name="CONTACT"),
    path("Registrationofemployee", views.REGIEMP, name="REGIEMP"),
    path("ADMINLOGIN", views.ADMINLOGIN, name="ADMINLOGIN"),
    path("ABOUT", views.ABOUT, name="ABOUT"),
    path('Tasks', views.assign_task, name='Task'),
    path('task-list/', views.assigned_tasks, name='taskemployeelist'),
    path("employeesignuplogin", views.employeesignuplogin, name="employeesignuplogin"),
    path("REGIEMP", views.REGIEMP, name="REGIEMP"),
    path("Developers", views.DEV, name="Developers"),
    path("REGIDMENT", views.REGIDMENT, name="REGIDMENT"),
    path("ADMINLOGIN/AdminDashboard",views.AdminDashboard,name="AdminDashboard"),
    path('AdminDashboard/assigned-tasks/', views.assigned_tasks, name='assigned_tasks'),
    path('AdminDashboard/task-des/', views.task_des, name='task_des'),
    path('mark_task_finished/<int:task_id>/<email>/', views.mark_task_finished, name='mark_task_finished'),
    path('AdminDashboard/task-end-dates/', views.task_end_dates, name='task_end_dates'),
    path('EMPTaskEndDate', views.EMPTaskEndDate, name='EMPTaskEndDate'),
    path('logout/', views.logout, name='logout'),
    path('ADMINLOGIN/AdminDashboard/emplist', views.employee_list, name='employee_list'),   
    path('delete/<int:pk>/', views.delete_employee, name='delete_employee'),
    path('edit/<int:pk>/', views.edit_employee, name='edit_employee'),
    path('departments/', views.department_list, name='department_list'),
    path('search/', views.search_employee, name='search_employee'),
    path('Dlist/', views.department_list, name='Dlist'),
    path('search_department/', views.search_department, name='search_department'),
    path('edit_department/<int:department_id>/',views.edit_department, name='edit_department'),
    path('delete_department/<int:department_id>/',views.delete_department, name='delete_department'),
    path('AdminDashboard/TaskReport', views.TaskReport, name='TaskReport'),
    path('EMPDashboard', views.EMPDASHBOARD, name='EMPDashboard'),
    path('EMPAccount', views.EMPAccount, name='EMPAccount'),
    path('EmployeeTask', views.EmployeeTask, name='EmployeeTask'),
    path('TaskDashboard', views.TaskDashboard, name='TaskDashboard'),
    path('finished-tasks/', views.finished_tasks_view, name='finished_tasks'),
    path('employee_dashboard/', views.employee_dashboard, name='employee_dashboard'),
    path('update_assignment/<int:task_id>/', views.update_Assignment, name='update_assignment'),
    path('Chamcong', views.timesheet_view, name='Chamcong'),
]
